version: "3.0" # specify docker-compose version

# Define the services/ containers to be run
services:
  productservice: # name of the first service
    build: productserv # specify the directory of the Dockerfile
    ports:
      - "4001:4001" # specify port mapping
    links:
      - database # link this service to the database service

  orderservice: # name of the second service
    build: orderserv # specify the directory of the Dockerfile
    ports:
      - "4002:4002" #specify ports mapping
    links:
      - database # link this service to the database service

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding
